In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import statsmodels.api as sm


In [2]:
data = pd.read_csv('startup.csv')
data.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [3]:
real_x = data.iloc[:,0:4].values
real_y = data.iloc[:,4].values

real_x



array([[165349.2, 136897.8, 471784.1, 'New York'],
       [162597.7, 151377.59, 443898.53, 'California'],
       [153441.51, 101145.55, 407934.54, 'Florida'],
       [144372.41, 118671.85, 383199.62, 'New York'],
       [142107.34, 91391.77, 366168.42, 'Florida'],
       [131876.9, 99814.71, 362861.36, 'New York'],
       [134615.46, 147198.87, 127716.82, 'California'],
       [130298.13, 145530.06, 323876.68, 'Florida'],
       [120542.52, 148718.95, 311613.29, 'New York'],
       [123334.88, 108679.17, 304981.62, 'California'],
       [101913.08, 110594.11, 229160.95, 'Florida'],
       [100671.96, 91790.61, 249744.55, 'California'],
       [93863.75, 127320.38, 249839.44, 'Florida'],
       [91992.39, 135495.07, 252664.93, 'California'],
       [119943.24, 156547.42, 256512.92, 'Florida'],
       [114523.61, 122616.84, 261776.23, 'New York'],
       [78013.11, 121597.55, 264346.06, 'California'],
       [94657.16, 145077.58, 282574.31, 'New York'],
       [91749.16, 114175.79, 29491

In [4]:
en = pd.get_dummies(data , columns=['State'])
en.insert(7,column="Profit1",value=data.iloc[:,4])

In [5]:
en.drop("Profit",axis=1,inplace=True)


In [6]:
en.head()

R&D Spend  Administration  Marketing Spend  State_California  \
0  165349.20       136897.80        471784.10                 0   
1  162597.70       151377.59        443898.53                 1   
2  153441.51       101145.55        407934.54                 0   
3  144372.41       118671.85        383199.62                 0   
4  142107.34        91391.77        366168.42                 0   

   State_Florida  State_New York    Profit1  
0              0               1  192261.83  
1              0               0  191792.06  
2              1               0  191050.39  
3              0               1  182901.99  
4              1               0  166187.94

In [7]:
en.columns = ['R&D Spend','Administration',"Marketing Spend",'State_California','State_Florida','State_New York','Profit']

In [8]:
real_x = en.iloc[:,0:6].values
real_y = en.iloc[:,6].values


In [9]:
real_x = en.iloc[:,1:].values

In [9]:
train_x,test_x,train_y,test_y = train_test_split(real_x,real_y,test_size=0.3,random_state=0)

In [10]:
lin = LinearRegression()
lin.fit(train_x,train_y)


LinearRegression()

In [11]:
pred_y = lin.predict(test_x)

In [12]:
pred_y

array([104282.76472171, 132536.88499212, 133910.85007767,  72584.77489417,
       179920.9276189 , 114549.31079233,  66444.43261347,  98404.96840122,
       114499.82808602, 169367.50639895,  96522.6253998 ,  88040.6718287 ,
       110949.99405525,  90419.1897851 , 128020.46250064])

In [13]:
test_y

array([103282.38, 144259.4 , 146121.95,  77798.83, 191050.39, 105008.31,
        81229.06,  97483.56, 110352.25, 166187.94,  96778.92,  96479.51,
       105733.54,  96712.8 , 124266.9 ])

In [14]:
104282.76472171-103282.38

1000.3847217099974

In [15]:
lin.coef_

array([-1.74026449e-16,  3.33066907e-16,  2.91583341e-12, -1.63905627e-12,
       -1.27670664e-12,  1.00000000e+00])

In [16]:
lin.intercept_

-1.0186340659856796e-10

In [15]:
real_x = np.append(arr=np.ones((50,1)),values=real_x,axis=1)

In [16]:
x_opt = real_x[:,[0,1,2,3,4,5]]

In [17]:
reg_OLS = sm.OLS(endog=real_y,exog=x_opt).fit()

In [18]:
reg_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.951
Model:                            OLS   Adj. R-squared:                  0.945
Method:                 Least Squares   F-statistic:                     169.9
Date:                Sun, 10 Jan 2021   Prob (F-statistic):           1.34e-27
Time:                        08:35:02   Log-Likelihood:                -525.38
No. Observations:                  50   AIC:                             1063.
Df Residuals:                      44   BIC:                             1074.
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       5.008e+04   6952.587      7.204      0.000    3.61e+04    6.41e+04
x1             0.8060      0.046     17.369      0.000       0.712       0.900
x2            -0.0270      0.052     -0.517      0.608      -0.132       0.078
x3             0.0270      0.017      1.574      0.123      -0.008       0.062
x4            41.8870   3256.039      0.013      0.990   -6520.229    6604.003
x5           240.6758   3338.857      0.072      0.943   -6488.349    6969.701
==============================================================================
Omnibus:                       14.782   Durbin-Watson:                   1.283
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               21.266
Skew:                          -0.948   Prob(JB):                     2.41e-05
Kurtosis:                       5.572   Cond. No.                     1.47e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.47e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [32]:
x_opt = real_x[:,[0,1]]
reg_OLS = sm.OLS(endog=real_y,exog=x_opt).fit()
reg_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.947
Model:                            OLS   Adj. R-squared:                  0.945
Method:                 Least Squares   F-statistic:                     849.8
Date:                Sun, 10 Jan 2021   Prob (F-statistic):           3.50e-32
Time:                        08:37:14   Log-Likelihood:                -527.44
No. Observations:                  50   AIC:                             1059.
Df Residuals:                      48   BIC:                             1063.
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       4.903e+04   2537.897     19.320      0.000    4.39e+04    5.41e+04
x1             0.8543      0.029     29.151      0.000       0.795       0.913
==============================================================================
Omnibus:                       13.727   Durbin-Watson:                   1.116
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               18.536
Skew:                          -0.911   Prob(JB):                     9.44e-05
Kurtosis:                       5.361   Cond. No.                     1.65e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.65e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [33]:
train_x,test_x,train_y,test_y = train_test_split(x_opt,real_y,test_size=0.3,random_state=0)

In [34]:
lin = LinearRegression()
lin.fit(train_x,train_y)


LinearRegression()

In [35]:
pred_y = lin.predict(test_x)

In [36]:
pred_y

array([104347.29054818, 134059.15325094, 135124.30398379,  71598.91750239,
       179346.89726824, 109544.72355241,  65022.1146424 , 100129.03206143,
       111164.14538661, 169619.71578557,  95286.60066917,  87150.76014861,
       112309.27339546,  87504.38861279, 126401.4513695 ])

In [37]:
test_y

array([103282.38, 144259.4 , 146121.95,  77798.83, 191050.39, 105008.31,
        81229.06,  97483.56, 110352.25, 166187.94,  96778.92,  96479.51,
       105733.54,  96712.8 , 124266.9 ])

In [38]:
104347.29054818-103282.38


1064.9105481799925